name: licest

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      target: production
    restart: always
    environment:
      API_PORT: ${API_PORT}
      FRONTEND_PORT: ${FRONTEND_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public"
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    restart: always
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    depends_on:
      - api
